version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sh prepare_data.sh && python ./app/seed_with_psycopg.py && uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://mygames:mygames@db:5432/mygames
      - DATA_FOLDER=./app/data
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mygames
      - POSTGRES_PASSWORD=mygames
      - POSTGRES_DB=mygames

volumes:
  postgres_data:
